sudo: false
language: node_js
node_js:
- "6"
- "5"
- "4"
- "0.12"
- "0.10"
matrix:
  include:
  - node_js: "6"
    env:
    - NPM_INSTALL_PACKAGES=standard
    - NPM_RUN_SCRIPT=test-standard-coverage
  - node_js: "0.10"
    env:
    - NPM_INSTALL_PACKAGES=promise-polyfill
env: NPM_RUN_SCRIPT=test
install:
- npm install
- if [ -n "$NPM_INSTALL_PACKAGES" ]; then npm install $NPM_INSTALL_PACKAGES; fi
script:
- npm run $NPM_RUN_SCRIPT
